---
title: "Covenant of Majors"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
*La primer columna va a tener 650 pixels de ancho, despues que salto a los otras 
-----------------------------------------------------------------------
*esta linea hace que este como en una pagina nueva 


### Benchymarking de la implementacion de politicas sustentables

En este trabajo analizaremos que tan bien o que tan mal es el desempeño de los 
intendentes del municipio (las acciones de los municipios de Maipu, Ciudad, Las Heras....)

```{r}
co2 <- rnorm (50, 200, 30) 
#50 datos, promedi 200, desvio +-30
hist (co2)
#este es el histograma de siempre 

```

Column {data-width=350}
-----------------------------------------------------------------------

### Participacion de cada municipio

```{r}
muni <- c("capital", "Godoy Cruz", "Guaymallen", "Maipu", "Lujan", "Las Heras")
munico2 <- c (300, 250, 270, 320, 412, 330)
pie(munico2, labels = (muni))
#Ya vemos como genera un grafico de torta esto, esta bueno

```

### Transporte publico

```{r}


```
RSU (Residuos Solidos Urbanos) 
=============

```{r}


```


Reciclado 
=======
```{r}

```


RAE (Residuos de aparatos electricos y electronicos)
=======

```{r}


```

Benchmarking de intendentes
======

```{r}


```


#Asi subraya con las rayitas (-----)
#Con el ==== hace una hoja separada como un saltito